/*
 * This file was automatically generated by EvoSuite
 * Sun Mar 09 21:13:29 GMT 2025
 */

package maven;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import maven.Money;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Money_ESTest extends Money_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Money money0 = new Money(0, "");
      Money money1 = new Money(2981, "");
      boolean boolean0 = money0.equals(money1);
      assertFalse(boolean0);
      assertEquals(2981, money1.getAmount());
      assertFalse(money1.equals((Object)money0));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Money money0 = new Money(998, (String) null);
      money0.getCurrency();
      assertEquals(998, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Money money0 = new Money(0, "e/N-CN$;FW01*");
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Money money0 = new Money(0, "maven.Money");
      int int0 = money0.getAmount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Money money0 = new Money(2121, "z");
      int int0 = money0.getAmount();
      assertEquals(2121, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Money money0 = new Money(0, "KXy~9aH");
      Money money1 = money0.add(money0);
      assertEquals(0, money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Money money0 = new Money(1596, "");
      Money money1 = money0.add(money0);
      assertEquals(1596, money0.getAmount());
      assertEquals(3192, money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Money money0 = new Money(1596, "");
      Money money1 = new Money(1596, (String) null);
      // Undeclared exception!
      try { 
        money0.equals(money1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Money money0 = new Money(1052, "");
      // Undeclared exception!
      try { 
        money0.add((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("maven.Money", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Money money0 = new Money((-2666), "");
      money0.getCurrency();
      assertEquals((-2666), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Money money0 = new Money((-2211), "maven.Money");
      int int0 = money0.getAmount();
      assertEquals((-2211), int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Money money0 = new Money((-2040), "W");
      Money money1 = new Money((-2040), "V");
      boolean boolean0 = money1.equals(money0);
      assertEquals((-2040), money1.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Money money0 = new Money((-2040), "W");
      boolean boolean0 = money0.equals("W");
      assertEquals((-2040), money0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Money money0 = new Money((-2040), "W");
      boolean boolean0 = money0.equals(money0);
      assertEquals((-2040), money0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Money money0 = new Money((-2040), "W");
      Money money1 = money0.add(money0);
      boolean boolean0 = money0.equals(money1);
      assertEquals((-4080), money1.getAmount());
      assertFalse(money1.equals((Object)money0));
      assertEquals((-2040), money0.getAmount());
      assertFalse(boolean0);
  }
}
